name: DlowTheProducer
favicon: null
layout_spectrum: 0.9117993400432169
typography_spectrum: 0.353732637129724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9487831983715296
  lightness: 0.0869517910759896
  saturation: 0.0028543921653181314
  rhythmicContrast: 0.16431733407080173
purpose: []
