favicon: null
name: DlowTheProducer
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.002854392165318131
  brandStrength: 0.9487831983715296
  rhythmicContrast: 0.1643173340708017
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.0869517910759896
typography_spectrum: 0.3291517
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9117993400432169
analytics:
  twitter: null
  google: null
  facebook: null
